{"pageProps":{"page":{"slug":"class.underflowexception.md","content":"# Клас UnderflowException\n\n(PHP 5 >= 5.1.0, PHP 7, PHP 8)\n\n## Вступ\n\nВикидається виняток під час спроби зробити неприпустиму операцію над порожнім контейнером. Наприклад, таку як видалення елемента з порожнього контейнера.\n\n## Огляд класів\n\n```classsynopsis\n\n     \n      class UnderflowException\n     \n\n     \n      extends\n       RuntimeException\n      {\n\n     /* Наследуемые свойства */\n     \n      protected\n      string\n       $message = \"\";\nprivate\n      string\n       $string = \"\";\nprotected\n      int\n       $code;\nprotected\n      string\n       $file = \"\";\nprotected\n      int\n       $line;\nprivate\n      array\n       $trace = [];\nprivate\n      ?Throwable\n       $previous = null;\n\n\n     /* Наследуемые методы */\n     \n   public Exception::__construct(string $message = \"\", int $code = 0, ?Throwable $previous = null)\n\n     final public Exception::getMessage(): string\nfinal public Exception::getPrevious(): ?Throwable\nfinal public Exception::getCode(): int\nfinal public Exception::getFile(): string\nfinal public Exception::getLine(): int\nfinal public Exception::getTrace(): array\nfinal public Exception::getTraceAsString(): string\npublic Exception::__toString(): string\nprivate Exception::__clone(): void\n\n    }\n```\n","title":"Клас UnderflowException","contentType":2,"navigation":[{"class.runtimeexception.md":"« RuntimeException"},{"class.unexpectedvalueexception.md":"UnexpectedValueException »"},{"index.md":"PHP Manual"},{"spl.exceptions.md":"Винятки"}]}},"__N_SSG":true}