{"pageProps":{"page":{"slug":"class.dateinvalidoperationexception.md","content":"# Клас DateInvalidOperationException\n\n(PHP 8 >= 8.3.0)\n\n## Вступ\n\nВикидається методами [DateTimeImmutable::sub()](datetimeimmutable.sub.md) і [DateTime::sub()](datetime.sub.md) при спробі виконання операції, що не підтримується.\n\nПриклад такої непідтримуваної операції - це спроба відібрати, що зберігається в об'єкті. [DateInterval](class.dateinterval.md) тимчасовий інтервал начебто `next weekday` («наступний будній день» - англ.), що представляє відносну характеристику часу, оскільки неможливо побудувати зворотне логічне твердження.\n\n## Огляд класів\n\n```classsynopsis\n\n    \n     class DateInvalidOperationException\n    \n\n    \n     extends\n      DateException\n     {\n\n    /* Наследуемые свойства */\n    \n      protected\n      string\n       $message = \"\";\nprivate\n      string\n       $string = \"\";\nprotected\n      int\n       $code;\nprotected\n      string\n       $file = \"\";\nprotected\n      int\n       $line;\nprivate\n      array\n       $trace = [];\nprivate\n      ?Throwable\n       $previous = null;\n\n\n    /* Наследуемые методы */\n    \n   public Exception::__construct(string $message = \"\", int $code = 0, ?Throwable $previous = null)\n\n    final public Exception::getMessage(): string\nfinal public Exception::getPrevious(): ?Throwable\nfinal public Exception::getCode(): int\nfinal public Exception::getFile(): string\nfinal public Exception::getLine(): int\nfinal public Exception::getTrace(): array\nfinal public Exception::getTraceAsString(): string\npublic Exception::__toString(): string\nprivate Exception::__clone(): void\n\n   }\n```\n","title":"Клас DateInvalidOperationException","contentType":2,"navigation":[{"class.dateexception.md":"« DateException"},{"class.dateinvalidtimezoneexception.md":"DateInvalidTimeZoneException »"},{"index.md":"PHP Manual"},{"book.datetime.md":"Дата час"}]}},"__N_SSG":true}