{"pageProps":{"page":{"slug":"errorexception.getseverity.md","content":"# ErrorException::getSeverity\n\n(PHP 5 >= 5.1.0, PHP 7, PHP 8)\n\nErrorException::getSeverity — Отримує серйозність виключення\n\n### Опис\n\n```methodsynopsis\nfinal public ErrorException::getSeverity(): int\n```\n\nПовертає серйозність виключення.\n\n### Список параметрів\n\nЦя функція не має параметрів.\n\n### Значення, що повертаються\n\nПовертає рівень серйозності виключення.\n\n### Приклади\n\n**Приклад #1 Приклад використання** ErrorException::getSeverity()\\*\\*\\*\\*\n\n```php\n<?php\ntry {\n    throw new ErrorException(\"Сообщение об исключении\", 0, E_USER_ERROR);\n} catch(ErrorException $e) {\n    echo \"Серьёзность этого исключения равна: \" . $e->getSeverity();\n    var_dump($e->getSeverity() === E_USER_ERROR);\n}\n?>\n```\n\nВисновок наведеного прикладу буде схожим на:\n\n```\nСерьёзность этого исключения равна: 256\nbool(true)\n```\n","title":"ErrorException::getSeverity","contentType":2,"navigation":[{"errorexception.construct.md":"« ErrorException::\\_\\_construct"},{"class.closedgeneratorexception.md":"ClosedGeneratorException »"},{"index.md":"PHP Manual"},{"class.errorexception.md":"ErrorException"}]}},"__N_SSG":true}