{"pageProps":{"page":{"slug":"error.getprevious.md","content":"# Error::getPrevious\n\n(PHP 7, PHP 8)\n\nError::getPrevious — Повертає попередній Throwable\n\n### Опис\n\n```methodsynopsis\nfinal public Error::getPrevious(): ?Throwable\n```\n\nПовертає попередній об'єкт Throwable (третій параметр конструктора [Error::\\_\\_construct()](error.construct.md)\n\n### Список параметрів\n\nЦя функція не має параметрів.\n\n### Значення, що повертаються\n\nПовертає попередній об'єкт [Throwable](class.throwable.md), якщо він є, і \\*\\*`null`\\*\\*якщо його немає.\n\n### Приклади\n\n**Приклад #1 Приклад використання** Error::getPrevious()\\*\\*\\*\\*\n\nПрохід та друк ланцюга винятків.\n\n```php\n<?php\nclass MyCustomError extends Error {}\n\nfunction doStuff() {\n    try {\n        throw new InvalidArgumentError(\"Вы делаете это неправильно!\", 112);\n    } catch(Error $e) {\n        throw new MyCustomError(\"Что-то случилось\", 911, $e);\n    }\n}\n\n\ntry {\n    doStuff();\n} catch(Error $e) {\n    do {\n        printf(\"%s:%d %s (%d) [%s]\\n\", $e->getFile(), $e->getLine(), $e->getMessage(), $e->getCode(), get_class($e));\n    } while($e = $e->getPrevious());\n}\n?>\n```\n\nВисновок наведеного прикладу буде схожим на:\n\n```\n/home/bjori/ex.php:8 Что-то случилось (911) [MyCustomError]\n/home/bjori/ex.php:6 Вы делаете это неправильно! (112) [InvalidArgumentError]\n```\n\n### Дивіться також\n\n-   [Throwable::getPrevious()](throwable.getprevious.md) \\- Повертає попередній Throwable\n","title":"Error::getPrevious","contentType":2,"navigation":[{"error.getmessage.md":"« Error::getMessage"},{"error.getcode.md":"Error::getCode »"},{"index.md":"PHP Manual"},{"class.error.md":"Error"}]}},"__N_SSG":true}